const zh: Record<string, string> = {
  'Custom Endpoints': '自定义端点',
  Active: '使用中',
  'API key set': '已设置 API 密钥',
  Activate: '启用',
  Delete: '删除',
  'Add an OpenAI-compatible endpoint below.': '在下方添加兼容 OpenAI API 的端点。',
  'No custom endpoints': '尚未配置自定义端点',
  'Edit Endpoint': '编辑端点',
  'Add Endpoint': '添加端点',
  Name: '名称',
  'Provider ID': '提供方 ID',
  'Endpoint URL': '端点 URL',
  'Default Model': '默认模型',
  Context: '上下文长度',
  Auto: '自动',
  'API Key': 'API 密钥',
  'Leave blank to keep current key': '留空以保留当前密钥',
  Optional: '可选',
  'Use for new chats': '用于新会话',
  'Discover models': '自动获取模型',
  Test: '测试连接',
  Save: '保存',
  'New endpoint': '新建端点',
  'Could not load custom endpoints': '无法加载自定义端点',
  'Custom endpoint saved.': '自定义端点已保存。',
  'Save failed': '保存失败',
  'Endpoint is reachable.': '端点连接正常。',
  'Endpoint validation failed.': '端点验证失败。',
  'Validation failed': '验证失败',
  'Activation failed': '启用失败',
  'Delete failed': '删除失败'
}

export const customEndpointText = (locale: string, text: string) => (locale === 'zh' ? (zh[text] ?? text) : text)
